/* The following code was generated by JFlex 1.6.1 */

// Alloy Analyzer 4 -- Copyright (c) 2006-2008, Felix Chang
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files
// (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify,
// merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
// OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

package edu.mit.csail.sdg.parser;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorSyntax;
import edu.mit.csail.sdg.alloy4.Pos;
import edu.mit.csail.sdg.alloy4.Version;
import edu.mit.csail.sdg.ast.ExprConstant;
import edu.mit.csail.sdg.ast.ExprVar;
import java.util.List;
import java_cup.runtime.*;

/** Autogenerated by JFlex 1.4.1 */


public final class CompLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\125\1\126\1\111\1\112\1\113\1\111\16\125\4\0\1\126\1\1"+
    "\1\107\1\2\1\124\1\0\1\3\1\115\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\13\1\14\1\116\1\121\10\122\1\15\1\0\1\16"+
    "\1\17\1\12\1\0\1\20\1\120\1\63\1\75\3\120\2\124\1\56"+
    "\11\124\1\61\7\124\1\21\1\110\1\22\1\23\1\117\1\0\1\30"+
    "\1\31\1\35\1\40\1\41\1\55\1\60\1\43\1\45\1\46\1\44"+
    "\1\36\1\50\1\37\1\47\1\54\1\57\1\34\1\32\1\33\1\42"+
    "\1\53\1\124\1\51\1\52\1\124\1\24\1\25\1\26\1\27\6\125"+
    "\1\114\32\125\2\0\4\123\4\0\1\123\2\0\1\125\7\0\1\123"+
    "\4\0\1\123\5\0\27\123\1\0\37\123\1\0\u01ca\123\4\0\14\123"+
    "\16\0\5\123\7\0\1\123\1\0\1\123\21\0\160\125\5\123\1\0"+
    "\2\123\2\0\4\123\10\0\1\123\1\0\3\123\1\0\1\123\1\0"+
    "\24\123\1\0\123\123\1\0\213\123\1\0\5\125\2\0\236\123\11\0"+
    "\46\123\2\0\1\123\7\0\47\123\7\0\1\123\1\0\55\125\1\0"+
    "\1\125\1\0\2\125\1\0\2\125\1\0\1\125\10\0\33\123\5\0"+
    "\3\123\15\0\5\125\6\0\1\123\4\0\13\125\5\0\53\123\37\125"+
    "\4\0\2\123\1\125\143\123\1\0\1\123\10\125\1\0\6\125\2\123"+
    "\2\125\1\0\4\125\2\123\12\125\3\123\2\0\1\123\17\0\1\125"+
    "\1\123\1\125\36\123\33\125\2\0\131\123\13\125\1\123\16\0\12\125"+
    "\41\123\11\125\2\123\4\0\1\123\5\0\26\123\4\125\1\123\11\125"+
    "\1\123\3\125\1\123\5\125\22\0\31\123\3\125\104\0\1\123\1\0"+
    "\13\123\67\0\33\125\1\0\4\125\66\123\3\125\1\123\22\125\1\123"+
    "\7\125\12\123\2\125\2\0\12\125\1\0\7\123\1\0\7\123\1\0"+
    "\3\125\1\0\10\123\2\0\2\123\2\0\26\123\1\0\7\123\1\0"+
    "\1\123\3\0\4\123\2\0\1\125\1\123\7\125\2\0\2\125\2\0"+
    "\3\125\1\123\10\0\1\125\4\0\2\123\1\0\3\123\2\125\2\0"+
    "\12\125\4\123\7\0\1\123\5\0\3\125\1\0\6\123\4\0\2\123"+
    "\2\0\26\123\1\0\7\123\1\0\2\123\1\0\2\123\1\0\2\123"+
    "\2\0\1\125\1\0\5\125\4\0\2\125\2\0\3\125\3\0\1\125"+
    "\7\0\4\123\1\0\1\123\7\0\14\125\3\123\1\125\13\0\3\125"+
    "\1\0\11\123\1\0\3\123\1\0\26\123\1\0\7\123\1\0\2\123"+
    "\1\0\5\123\2\0\1\125\1\123\10\125\1\0\3\125\1\0\3\125"+
    "\2\0\1\123\17\0\2\123\2\125\2\0\12\125\1\0\1\123\17\0"+
    "\3\125\1\0\10\123\2\0\2\123\2\0\26\123\1\0\7\123\1\0"+
    "\2\123\1\0\5\123\2\0\1\125\1\123\7\125\2\0\2\125\2\0"+
    "\3\125\10\0\2\125\4\0\2\123\1\0\3\123\2\125\2\0\12\125"+
    "\1\0\1\123\20\0\1\125\1\123\1\0\6\123\3\0\3\123\1\0"+
    "\4\123\3\0\2\123\1\0\1\123\1\0\2\123\3\0\2\123\3\0"+
    "\3\123\3\0\14\123\4\0\5\125\3\0\3\125\1\0\4\125\2\0"+
    "\1\123\6\0\1\125\16\0\12\125\11\0\1\123\7\0\3\125\1\0"+
    "\10\123\1\0\3\123\1\0\27\123\1\0\12\123\1\0\5\123\3\0"+
    "\1\123\7\125\1\0\3\125\1\0\4\125\7\0\2\125\1\0\2\123"+
    "\6\0\2\123\2\125\2\0\12\125\22\0\2\125\1\0\10\123\1\0"+
    "\3\123\1\0\27\123\1\0\12\123\1\0\5\123\2\0\1\125\1\123"+
    "\7\125\1\0\3\125\1\0\4\125\7\0\2\125\7\0\1\123\1\0"+
    "\2\123\2\125\2\0\12\125\1\0\2\123\17\0\2\125\1\0\10\123"+
    "\1\0\3\123\1\0\51\123\2\0\1\123\7\125\1\0\3\125\1\0"+
    "\4\125\1\123\10\0\1\125\10\0\2\123\2\125\2\0\12\125\12\0"+
    "\6\123\2\0\2\125\1\0\22\123\3\0\30\123\1\0\11\123\1\0"+
    "\1\123\2\0\7\123\3\0\1\125\4\0\6\125\1\0\1\125\1\0"+
    "\10\125\22\0\2\125\15\0\60\123\1\125\2\123\7\125\4\0\10\123"+
    "\10\125\1\0\12\125\47\0\2\123\1\0\1\123\2\0\2\123\1\0"+
    "\1\123\2\0\1\123\6\0\4\123\1\0\7\123\1\0\3\123\1\0"+
    "\1\123\1\0\1\123\2\0\2\123\1\0\4\123\1\125\2\123\6\125"+
    "\1\0\2\125\1\123\2\0\5\123\1\0\1\123\1\0\6\125\2\0"+
    "\12\125\2\0\4\123\40\0\1\123\27\0\2\125\6\0\12\125\13\0"+
    "\1\125\1\0\1\125\1\0\1\125\4\0\2\125\10\123\1\0\44\123"+
    "\4\0\24\125\1\0\2\125\5\123\13\125\1\0\44\125\11\0\1\125"+
    "\71\0\53\123\24\125\1\123\12\125\6\0\6\123\4\125\4\123\3\125"+
    "\1\123\3\125\2\123\7\125\3\123\4\125\15\123\14\125\1\123\17\125"+
    "\2\0\46\123\1\0\1\123\5\0\1\123\2\0\53\123\1\0\u014d\123"+
    "\1\0\4\123\2\0\7\123\1\0\1\123\1\0\4\123\2\0\51\123"+
    "\1\0\4\123\2\0\41\123\1\0\4\123\2\0\7\123\1\0\1\123"+
    "\1\0\4\123\2\0\17\123\1\0\71\123\1\0\4\123\2\0\103\123"+
    "\2\0\3\125\40\0\20\123\20\0\125\123\14\0\u026c\123\2\0\21\123"+
    "\1\0\32\123\5\0\113\123\3\0\3\123\17\0\15\123\1\0\4\123"+
    "\3\125\13\0\22\123\3\125\13\0\22\123\2\125\14\0\15\123\1\0"+
    "\3\123\1\0\2\125\14\0\64\123\40\125\3\0\1\123\3\0\2\123"+
    "\1\125\2\0\12\125\41\0\3\125\2\0\12\125\6\0\130\123\10\0"+
    "\51\123\1\125\1\123\5\0\106\123\12\0\35\123\3\0\14\125\4\0"+
    "\14\125\12\0\12\125\36\123\2\0\5\123\13\0\54\123\4\0\21\125"+
    "\7\123\2\125\6\0\12\125\46\0\27\123\5\125\4\0\65\123\12\125"+
    "\1\0\35\125\2\0\13\125\6\0\12\125\15\0\1\123\130\0\5\125"+
    "\57\123\21\125\7\123\4\0\12\125\21\0\11\125\14\0\3\125\36\123"+
    "\15\125\2\123\12\125\54\123\16\125\14\0\44\123\24\125\10\0\12\125"+
    "\3\0\3\123\12\125\44\123\122\0\3\125\1\0\25\125\4\123\1\125"+
    "\4\123\3\125\2\123\11\0\300\123\47\125\25\0\4\125\u0110\123\1\62"+
    "\5\123\2\0\6\123\2\0\46\123\2\0\6\123\2\0\10\123\1\0"+
    "\1\123\1\0\1\123\1\0\1\123\1\0\37\123\2\0\65\123\1\0"+
    "\7\123\1\0\1\123\3\0\3\123\1\0\7\123\3\0\4\123\2\0"+
    "\6\123\4\0\15\123\5\0\3\123\1\0\7\123\16\0\5\125\30\0"+
    "\1\112\1\112\5\125\20\0\2\123\23\0\1\123\13\0\5\125\5\0"+
    "\6\125\1\0\1\123\15\0\1\123\20\0\15\123\3\0\33\123\25\0"+
    "\15\125\4\0\1\125\3\0\14\125\21\0\1\123\4\0\1\123\2\0"+
    "\12\123\1\0\1\123\3\0\5\123\6\0\1\123\1\0\1\123\1\0"+
    "\1\123\1\0\4\123\1\0\13\123\2\0\4\123\5\0\5\123\4\0"+
    "\1\123\21\0\51\123\u05f7\0\1\64\1\65\1\66\1\67\1\70\1\71"+
    "\1\72\1\73\1\74\1\0\1\76\1\77\1\100\1\101\1\102\1\103"+
    "\1\104\1\105\1\106\u046d\0\57\123\1\0\57\123\1\0\205\123\6\0"+
    "\4\123\3\125\2\123\14\0\46\123\1\0\1\123\5\0\1\123\2\0"+
    "\70\123\7\0\1\123\17\0\1\125\27\123\11\0\7\123\1\0\7\123"+
    "\1\0\7\123\1\0\7\123\1\0\7\123\1\0\7\123\1\0\7\123"+
    "\1\0\7\123\1\0\40\125\57\0\1\123\u01d5\0\3\123\31\0\11\123"+
    "\6\125\1\0\5\123\2\0\5\123\4\0\126\123\2\0\2\125\2\0"+
    "\3\123\1\0\132\123\1\0\4\123\5\0\51\123\3\0\136\123\21\0"+
    "\33\123\65\0\20\123\u0200\0\u19b6\123\112\0\u51cd\123\63\0\u048d\123\103\0"+
    "\56\123\2\0\u010d\123\3\0\20\123\12\125\2\123\24\0\57\123\1\125"+
    "\4\0\12\125\1\0\31\123\7\0\1\125\120\123\2\125\45\0\11\123"+
    "\2\0\147\123\2\0\4\123\1\0\4\123\14\0\13\123\115\0\12\123"+
    "\1\125\3\123\1\125\4\123\1\125\27\123\5\125\20\0\1\123\7\0"+
    "\64\123\14\0\2\125\62\123\21\125\13\0\12\125\6\0\22\125\6\123"+
    "\3\0\1\123\4\0\12\125\34\123\10\125\2\0\27\123\15\125\14\0"+
    "\35\123\3\0\4\125\57\123\16\125\16\0\1\123\12\125\46\0\51\123"+
    "\16\125\11\0\3\123\1\125\10\123\2\125\2\0\12\125\6\0\27\123"+
    "\3\0\1\123\1\125\4\0\60\123\1\125\1\123\3\125\2\123\2\125"+
    "\5\123\2\125\1\123\1\125\1\123\30\0\3\123\2\0\13\123\5\125"+
    "\2\0\3\123\2\125\12\0\6\123\2\0\6\123\2\0\6\123\11\0"+
    "\7\123\1\0\7\123\221\0\43\123\10\125\1\0\2\125\2\0\12\125"+
    "\6\0\u2ba4\123\14\0\27\123\4\0\61\123\u2104\0\u016e\123\2\0\152\123"+
    "\46\0\7\123\14\0\5\123\5\0\1\123\1\125\12\123\1\0\15\123"+
    "\1\0\5\123\1\0\1\123\1\0\2\123\1\0\2\123\1\0\154\123"+
    "\41\0\u016b\123\22\0\100\123\2\0\66\123\50\0\15\123\3\0\20\125"+
    "\20\0\7\125\14\0\2\123\30\0\3\123\31\0\1\123\6\0\5\123"+
    "\1\0\207\123\2\0\1\125\4\0\1\123\13\0\12\125\7\0\32\123"+
    "\4\0\1\123\1\0\32\123\13\0\131\123\3\0\6\123\2\0\6\123"+
    "\2\0\6\123\2\0\3\123\3\0\2\123\3\0\2\123\22\0\3\125"+
    "\4\0\14\123\1\0\32\123\1\0\23\123\1\0\2\123\1\0\17\123"+
    "\2\0\16\123\42\0\173\123\105\0\65\123\210\0\1\125\202\0\35\123"+
    "\3\0\61\123\57\0\37\123\21\0\33\123\65\0\36\123\2\0\44\123"+
    "\4\0\10\123\1\0\5\123\52\0\236\123\2\0\12\125\u0356\0\6\123"+
    "\2\0\1\123\1\0\54\123\1\0\2\123\3\0\1\123\2\0\27\123"+
    "\252\0\26\123\12\0\32\123\106\0\70\123\6\0\2\123\100\0\1\123"+
    "\3\125\1\0\2\125\5\0\4\125\4\123\1\0\3\123\1\0\33\123"+
    "\4\0\3\125\4\0\1\125\40\0\35\123\203\0\66\123\12\0\26\123"+
    "\12\0\23\123\215\0\111\123\u03b7\0\3\125\65\123\17\125\37\0\12\125"+
    "\20\0\3\125\55\123\13\125\2\0\1\125\22\0\31\123\7\0\12\125"+
    "\6\0\3\125\44\123\16\125\1\0\12\125\100\0\3\125\60\123\16\125"+
    "\4\123\13\0\12\125\u04a6\0\53\123\15\125\10\0\12\125\u0936\0\u036f\123"+
    "\221\0\143\123\u0b9d\0\u042f\123\u33d1\0\u0239\123\u04c7\0\105\123\13\0\1\123"+
    "\56\125\20\0\4\125\15\123\u4060\0\2\123\u2163\0\5\125\3\0\26\125"+
    "\2\0\7\125\36\0\4\125\224\0\3\125\u01bb\0\125\123\1\0\107\123"+
    "\1\0\2\123\2\0\1\123\2\0\2\123\2\0\4\123\1\0\14\123"+
    "\1\0\1\123\1\0\7\123\1\0\101\123\1\0\4\123\2\0\10\123"+
    "\1\0\7\123\1\0\34\123\1\0\4\123\1\0\5\123\1\0\1\123"+
    "\3\0\7\123\1\0\u0154\123\2\0\31\123\1\0\31\123\1\0\37\123"+
    "\1\0\31\123\1\0\37\123\1\0\31\123\1\0\37\123\1\0\31\123"+
    "\1\0\37\123\1\0\31\123\1\0\10\123\2\0\62\125\u1600\0\4\123"+
    "\1\0\33\123\1\0\2\123\1\0\1\123\2\0\1\123\1\0\12\123"+
    "\1\0\4\123\1\0\1\123\1\0\1\123\6\0\1\123\4\0\1\123"+
    "\1\0\1\123\1\0\1\123\1\0\3\123\1\0\2\123\1\0\1\123"+
    "\2\0\1\123\1\0\1\123\1\0\1\123\1\0\1\123\1\0\1\123"+
    "\1\0\2\123\1\0\1\123\2\0\4\123\1\0\7\123\1\0\4\123"+
    "\1\0\4\123\1\0\1\123\1\0\12\123\1\0\21\123\5\0\3\123"+
    "\1\0\5\123\1\0\21\123\u1144\0\ua6d7\123\51\0\u1035\123\13\0\336\123"+
    "\u3fe2\0\u021e\123\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\125\36\0\140\125\200\0\360\125\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\24\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\2\56\1\57"+
    "\1\60\1\55\1\61\1\62\1\63\1\0\1\64\1\65"+
    "\1\66\1\67\1\70\1\67\1\71\1\31\1\72\14\31"+
    "\1\73\5\31\1\74\3\31\1\71\12\31\1\75\1\76"+
    "\1\77\1\0\3\100\1\101\2\0\1\102\2\31\1\103"+
    "\1\57\1\104\1\105\1\106\1\107\1\110\2\31\1\111"+
    "\1\31\1\112\1\31\1\2\6\31\1\113\2\31\1\114"+
    "\2\31\1\102\1\115\6\31\1\116\1\117\1\120\1\31"+
    "\1\121\1\122\1\100\1\123\1\0\1\55\2\31\1\124"+
    "\1\125\1\31\1\126\1\127\1\130\1\131\1\132\4\31"+
    "\1\133\1\134\1\31\1\135\1\31\1\136\1\137\1\31"+
    "\1\140\3\31\1\141\13\31\1\142\4\31\1\143\1\31"+
    "\1\144\2\31\1\145\2\31\1\146\1\147\1\31\1\70"+
    "\1\31\1\150\1\151\1\130\3\31\1\136\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\127\0\127\0\127\0\256\0\127\0\127\0\127"+
    "\0\u0105\0\127\0\u015c\0\u01b3\0\127\0\u020a\0\u0261\0\u02b8"+
    "\0\u030f\0\127\0\127\0\127\0\127\0\127\0\u0366\0\127"+
    "\0\127\0\u03bd\0\u0414\0\u046b\0\u04c2\0\u0519\0\u0570\0\u05c7"+
    "\0\u061e\0\u0675\0\u06cc\0\u0723\0\u077a\0\u07d1\0\u0828\0\u087f"+
    "\0\u08d6\0\u092d\0\u0984\0\u09db\0\u0a32\0\127\0\127\0\127"+
    "\0\127\0\127\0\127\0\127\0\127\0\127\0\127\0\127"+
    "\0\127\0\127\0\127\0\127\0\127\0\127\0\127\0\u0a89"+
    "\0\127\0\u0ae0\0\u0b37\0\127\0\127\0\u0b8e\0\127\0\u0be5"+
    "\0\127\0\u0c3c\0\127\0\127\0\127\0\u0c93\0\127\0\127"+
    "\0\127\0\u0cea\0\u0d41\0\u0d98\0\u0def\0\u0e46\0\u0e9d\0\u0ef4"+
    "\0\u0f4b\0\u0fa2\0\u0ff9\0\u1050\0\u10a7\0\u10fe\0\u1155\0\u11ac"+
    "\0\u1203\0\u125a\0\u12b1\0\u1308\0\u135f\0\u13b6\0\u140d\0\u1464"+
    "\0\u14bb\0\u077a\0\u1512\0\u1569\0\u15c0\0\u1617\0\u166e\0\u16c5"+
    "\0\u171c\0\u1773\0\u17ca\0\u1821\0\u077a\0\u077a\0\u1878\0\u18cf"+
    "\0\u1926\0\u197d\0\u19d4\0\127\0\u1a2b\0\u1a82\0\127\0\u1ad9"+
    "\0\u1b30\0\u077a\0\u077a\0\u077a\0\u077a\0\u077a\0\u077a\0\u077a"+
    "\0\u1b87\0\u1bde\0\u077a\0\u1c35\0\u077a\0\u1c8c\0\u077a\0\u1ce3"+
    "\0\u1d3a\0\u1d91\0\u1de8\0\u1e3f\0\u1e96\0\u1eed\0\u1f44\0\u1f9b"+
    "\0\u077a\0\u1ff2\0\u2049\0\u077a\0\u077a\0\u20a0\0\u20f7\0\u214e"+
    "\0\u21a5\0\u21fc\0\u2253\0\u077a\0\u077a\0\u077a\0\u22aa\0\u1878"+
    "\0\u197d\0\u2301\0\u19d4\0\u2358\0\u1a2b\0\u23af\0\u2406\0\u077a"+
    "\0\u077a\0\u245d\0\u077a\0\u077a\0\u24b4\0\u077a\0\u077a\0\u250b"+
    "\0\u2562\0\u25b9\0\u2610\0\u077a\0\u077a\0\u2667\0\u077a\0\u26be"+
    "\0\u2715\0\u077a\0\u276c\0\u077a\0\u27c3\0\u281a\0\u2871\0\u077a"+
    "\0\u28c8\0\u291f\0\u2976\0\u29cd\0\u2a24\0\u2a7b\0\u2ad2\0\u2b29"+
    "\0\u2b80\0\u2bd7\0\u2c2e\0\u077a\0\u2c85\0\u2cdc\0\u2d33\0\u2d8a"+
    "\0\u077a\0\u2de1\0\u077a\0\u2e38\0\u2e8f\0\u077a\0\u2ee6\0\u2f3d"+
    "\0\u077a\0\u077a\0\u2f94\0\u077a\0\u2feb\0\u077a\0\u077a\0\u077a"+
    "\0\u3042\0\u3099\0\u30f0\0\u077a\0\u077a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\2\45\1\46\1\45\1\47\1\50"+
    "\3\45\1\51\1\52\1\53\2\45\1\54\1\55\1\45"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\1\66\1\45\1\67\1\70\1\71\1\72\1\73\1\74"+
    "\1\75\1\76\1\77\1\100\1\2\1\101\1\0\1\101"+
    "\1\0\1\2\1\102\2\45\2\103\2\45\1\2\1\101"+
    "\132\0\1\104\132\0\1\105\130\0\1\106\1\107\126\0"+
    "\1\110\4\0\1\111\115\0\1\112\5\0\1\106\124\0"+
    "\1\113\2\0\1\15\126\0\1\114\1\115\1\116\121\0"+
    "\1\117\3\0\1\120\135\0\1\121\131\0\1\45\1\122"+
    "\1\123\3\45\1\124\1\125\24\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\12\45\1\126\21\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\11\45\1\127"+
    "\1\130\2\45\1\131\1\45\1\132\14\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\13\45\1\133\20\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\12\45"+
    "\1\134\21\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\13\45\1\135\20\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\11\45\1\136\5\45\1\137\14\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\17\45"+
    "\1\140\14\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\15\45\1\141\16\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\6\45\1\142\1\143\11\45\1\144"+
    "\12\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\7\45\1\145\24\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\34\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\7\45\1\146\1\147\7\45\1\150\4\45"+
    "\1\151\6\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\4\45\1\152\2\45\1\153\14\45\1\154\7\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\17\45"+
    "\1\155\14\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\1\156\3\45\1\157\27\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\1\160\11\45\1\161\4\45"+
    "\1\162\14\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\7\45\1\163\24\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\3\45\1\164\30\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\33\45\1\165\11\0"+
    "\1\166\11\0\1\45\4\0\12\45\1\0\107\100\1\167"+
    "\1\170\16\100\30\0\1\171\1\172\17\171\1\173\10\171"+
    "\1\0\1\171\11\0\1\171\11\0\1\171\5\0\1\171"+
    "\1\103\2\171\2\103\1\0\1\171\32\0\32\171\1\0"+
    "\1\171\11\0\1\171\11\0\1\171\5\0\1\171\1\103"+
    "\2\171\2\103\1\0\1\171\2\0\111\106\1\101\15\106"+
    "\12\0\1\174\114\0\6\175\1\176\120\175\12\0\1\177"+
    "\144\0\2\45\1\200\31\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\2\45\1\201\31\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\6\45\1\202\25\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\10\45"+
    "\1\203\23\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\3\45\1\204\30\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\3\45\1\205\23\45\1\206\4\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\20\45"+
    "\1\207\13\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\30\45\1\210\3\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\20\45\1\211\13\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\15\45\1\212\16\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\7\45"+
    "\1\213\24\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\11\45\1\214\22\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\3\45\1\215\30\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\7\45\1\216\24\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\3\45"+
    "\1\217\3\45\1\220\24\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\2\45\1\221\31\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\2\45\1\222\31\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\12\45"+
    "\1\223\21\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\1\224\2\45\1\225\7\45\1\226\10\45\1\227"+
    "\7\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\15\45\1\230\16\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\3\45\1\231\30\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\11\45\1\232\22\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\24\45\1\233"+
    "\7\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\25\45\1\234\6\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\11\45\1\235\22\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\11\45\1\236\22\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\10\45\1\237"+
    "\23\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\4\45\1\240\27\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\11\45\1\241\3\45\1\242\16\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\5\45\1\243"+
    "\26\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\7\45\1\244\24\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\4\45\1\245\27\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\3\45\1\246\30\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\4\45\1\247"+
    "\27\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\32\250\1\0\1\250\11\0\1\250\11\0\1\250\5\0"+
    "\6\250\1\0\1\250\2\0\111\100\4\0\12\100\30\0"+
    "\32\171\1\0\1\171\11\0\1\171\11\0\1\171\5\0"+
    "\6\171\1\0\1\171\32\0\32\171\1\0\1\171\11\0"+
    "\1\171\11\0\1\171\5\0\1\171\2\251\1\171\1\251"+
    "\1\171\1\0\1\171\32\0\2\252\3\171\1\252\2\171"+
    "\2\252\13\171\1\252\4\171\1\0\1\252\11\0\1\252"+
    "\11\0\1\171\5\0\1\171\1\252\1\253\3\252\1\0"+
    "\1\171\2\0\6\175\1\254\126\175\1\254\5\175\1\255"+
    "\112\175\30\0\3\45\1\256\30\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\11\45\1\257\22\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\11\45\1\260"+
    "\22\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\2\45\1\261\31\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\5\45\1\262\26\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\11\45\1\263\22\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\11\45\1\264"+
    "\22\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\16\45\1\265\15\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\11\45\1\266\22\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\20\45\1\267\13\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\5\45\1\270"+
    "\26\45\11\0\1\45\11\0\1\45\4\0\12\45\31\0"+
    "\11\45\1\271\22\45\11\0\1\45\11\0\1\45\4\0"+
    "\12\45\31\0\1\272\33\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\11\45\1\273\22\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\23\45\1\274\10\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\7\45"+
    "\1\275\24\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\6\45\1\276\25\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\7\45\1\277\24\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\12\45\1\300\21\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\3\45"+
    "\1\301\30\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\10\45\1\302\23\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\23\45\1\303\10\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\3\45\1\304\30\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\15\45"+
    "\1\305\16\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\2\253\3\171\1\253\2\171\2\253\13\171\1\253"+
    "\4\171\1\0\1\253\11\0\1\253\11\0\1\171\5\0"+
    "\1\171\1\253\1\171\3\253\1\0\1\171\2\0\6\175"+
    "\1\254\5\175\1\101\112\175\30\0\4\45\1\306\27\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\4\45"+
    "\1\307\27\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\14\45\1\310\17\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\17\45\1\311\14\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\3\45\1\312\30\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\7\45"+
    "\1\313\24\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\12\45\1\314\21\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\5\45\1\315\26\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\15\45\1\316\16\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\6\45"+
    "\1\317\25\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\15\45\1\320\16\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\1\321\33\45\11\0\1\45\11\0"+
    "\1\45\4\0\12\45\31\0\7\45\1\322\24\45\11\0"+
    "\1\45\11\0\1\45\4\0\12\45\31\0\1\323\33\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\3\45"+
    "\1\324\30\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\15\45\1\325\16\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\6\45\1\326\25\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\10\45\1\327\23\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\2\45"+
    "\1\330\31\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\3\45\1\331\30\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\11\45\1\332\22\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\11\45\1\333\22\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\3\45"+
    "\1\334\30\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\3\45\1\335\30\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\30\45\1\336\3\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\5\45\1\337\26\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\7\45"+
    "\1\340\24\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\22\45\1\341\11\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\2\45\1\342\31\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\3\45\1\343\30\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\2\45"+
    "\1\344\31\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\15\45\1\345\16\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\11\45\1\346\22\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\3\45\1\347\30\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\3\45"+
    "\1\350\30\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\15\45\1\351\16\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\31\0\17\45\1\352\14\45\11\0\1\45"+
    "\11\0\1\45\4\0\12\45\31\0\23\45\1\353\10\45"+
    "\11\0\1\45\11\0\1\45\4\0\12\45\31\0\7\45"+
    "\1\354\24\45\11\0\1\45\11\0\1\45\4\0\12\45"+
    "\31\0\11\45\1\355\22\45\11\0\1\45\11\0\1\45"+
    "\4\0\12\45\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12615];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\1\1\3\11\1\1\1\11\2\1\1\11"+
    "\4\1\5\11\1\1\2\11\24\1\22\11\1\1\1\11"+
    "\2\1\2\11\1\1\1\11\1\1\1\11\1\0\3\11"+
    "\1\1\3\11\46\1\1\0\3\1\1\11\2\0\1\11"+
    "\54\1\1\0\101\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
 public String alloy_filename="";
 public int alloy_lineoffset=0; // If not zero, it is added to the current LINE NUMBER
 public List<Object> alloy_seenDollar;
 public CompModule alloy_module;
 private final Pos alloy_here(String txt) {
    return new Pos(alloy_filename,yycolumn+1,yyline+1+alloy_lineoffset,yycolumn+txt.length(),yyline+1);
 }
 private final Symbol alloy_sym(String txt, int type) {
    Pos p = alloy_here(txt); return new Symbol(type, p, p);
 }
 private final Symbol alloy_string(String txt) throws Err {
    Pos p = alloy_here(txt);
    if (!Version.experimental) throw new ErrorSyntax(p, "String literal is not currently supported.");
    StringBuilder sb = new StringBuilder(txt.length());
    for(int i=0; i<txt.length(); i++) {
       char c = txt.charAt(i);
       if (c=='\r' || c=='\n') throw new ErrorSyntax(p, "String literal cannot span multiple lines; use \\n instead.");
       if (c=='\\') {
          i++;
          if (i>=txt.length()) throw new ErrorSyntax(p, "String literal cannot end with a single \\");
          c = txt.charAt(i);
          if (c=='n') c='\n'; else if (c!='\'' && c!='\"' && c!='\\') throw new ErrorSyntax(p, "String literal currenty only supports\nfour escape sequences: \\\\, \\n, \\\', and \\\"");
       }
       sb.append(c);
    }
    txt = sb.toString();
    if (txt.length()==2) throw new ErrorSyntax(p, "Empty string is not allowed; try rewriting your model to use an empty set instead.");
    return new Symbol(CompSym.STR, p, ExprConstant.Op.STRING.make(p, txt));
 }
 private final Symbol alloy_id(String txt) throws Err {
    Pos p=alloy_here(txt);
    if (alloy_seenDollar.size()==0 && txt.indexOf('$')>=0) alloy_seenDollar.add(null);
    return new Symbol(CompSym.ID, p, ExprVar.make(p,txt));
 }
 private final Symbol alloy_num(String txt) throws Err {
    Pos p=alloy_here(txt);
    int n=0;
    try {
        txt = txt.replaceAll("_","");
        n=Integer.parseInt(txt);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The number "+txt+" " + ex);
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }
 private final Symbol alloy_hexnum(String txt) throws Err {
    Pos p=alloy_here(txt);
    int n=0;
    try {
        txt = txt.substring(2).replaceAll("_","");
        n=Integer.parseInt(txt, 16);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The hex number "+txt+" " + ex);
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }
 private final Symbol alloy_binarynum(String txt) throws Err {
    Pos p=alloy_here(txt);
    int n=0;
    try {
        txt = txt.substring(2).replaceAll("_","");
        n=Integer.parseInt(txt, 2);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The binary number "+txt+" " + ex);
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CompLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2924) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return new Symbol(CompSym.EOF, alloy_here(" "), alloy_here(" "));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new ErrorSyntax(alloy_here(" "), "Syntax error at the "+yytext()+" character. HEX: \\u"+Integer.toString(yytext().charAt(0),16)+")");
            }
          case 106: break;
          case 2: 
            { return alloy_sym(yytext(), CompSym.NOT         );
            }
          case 107: break;
          case 3: 
            { return alloy_sym(yytext(), CompSym.HASH        );
            }
          case 108: break;
          case 4: 
            { return alloy_sym(yytext(), CompSym.AMPERSAND   );
            }
          case 109: break;
          case 5: 
            { return alloy_sym(yytext(), CompSym.LPAREN      );
            }
          case 110: break;
          case 6: 
            { return alloy_sym(yytext(), CompSym.RPAREN      );
            }
          case 111: break;
          case 7: 
            { return alloy_sym(yytext(), CompSym.STAR        );
            }
          case 112: break;
          case 8: 
            { return alloy_sym(yytext(), CompSym.PLUS        );
            }
          case 113: break;
          case 9: 
            { return alloy_sym(yytext(), CompSym.COMMA       );
            }
          case 114: break;
          case 10: 
            { return alloy_sym(yytext(), CompSym.MINUS       );
            }
          case 115: break;
          case 11: 
            { return alloy_sym(yytext(), CompSym.GT          );
            }
          case 116: break;
          case 12: 
            { return alloy_sym(yytext(), CompSym.DOT         );
            }
          case 117: break;
          case 13: 
            { return alloy_sym(yytext(), CompSym.SLASH       );
            }
          case 118: break;
          case 14: 
            { return alloy_sym(yytext(), CompSym.COLON       );
            }
          case 119: break;
          case 15: 
            { return alloy_sym(yytext(), CompSym.LT          );
            }
          case 120: break;
          case 16: 
            { return alloy_sym(yytext(), CompSym.EQUALS      );
            }
          case 121: break;
          case 17: 
            { return alloy_sym(yytext(), CompSym.AT          );
            }
          case 122: break;
          case 18: 
            { return alloy_sym(yytext(), CompSym.LBRACKET    );
            }
          case 123: break;
          case 19: 
            { return alloy_sym(yytext(), CompSym.RBRACKET    );
            }
          case 124: break;
          case 20: 
            { return alloy_sym(yytext(), CompSym.CARET       );
            }
          case 125: break;
          case 21: 
            { return alloy_sym(yytext(), CompSym.LBRACE      );
            }
          case 126: break;
          case 22: 
            { return alloy_sym(yytext(), CompSym.BAR         );
            }
          case 127: break;
          case 23: 
            { return alloy_sym(yytext(), CompSym.RBRACE      );
            }
          case 128: break;
          case 24: 
            { return alloy_sym(yytext(), CompSym.TILDE       );
            }
          case 129: break;
          case 25: 
            { return alloy_id  (yytext());
            }
          case 130: break;
          case 26: 
            { return alloy_sym(yytext(), CompSym.PFEAT1       );
            }
          case 131: break;
          case 27: 
            { return alloy_sym(yytext(), CompSym.PFEAT2       );
            }
          case 132: break;
          case 28: 
            { return alloy_sym(yytext(), CompSym.PFEAT3       );
            }
          case 133: break;
          case 29: 
            { return alloy_sym(yytext(), CompSym.PFEAT4       );
            }
          case 134: break;
          case 30: 
            { return alloy_sym(yytext(), CompSym.PFEAT5       );
            }
          case 135: break;
          case 31: 
            { return alloy_sym(yytext(), CompSym.PFEAT6       );
            }
          case 136: break;
          case 32: 
            { return alloy_sym(yytext(), CompSym.PFEAT7       );
            }
          case 137: break;
          case 33: 
            { return alloy_sym(yytext(), CompSym.PFEAT8       );
            }
          case 138: break;
          case 34: 
            { return alloy_sym(yytext(), CompSym.PFEAT9       );
            }
          case 139: break;
          case 35: 
            { return alloy_sym(yytext(), CompSym.NFEAT1       );
            }
          case 140: break;
          case 36: 
            { return alloy_sym(yytext(), CompSym.NFEAT2       );
            }
          case 141: break;
          case 37: 
            { return alloy_sym(yytext(), CompSym.NFEAT3       );
            }
          case 142: break;
          case 38: 
            { return alloy_sym(yytext(), CompSym.NFEAT4       );
            }
          case 143: break;
          case 39: 
            { return alloy_sym(yytext(), CompSym.NFEAT5       );
            }
          case 144: break;
          case 40: 
            { return alloy_sym(yytext(), CompSym.NFEAT6       );
            }
          case 145: break;
          case 41: 
            { return alloy_sym(yytext(), CompSym.NFEAT7       );
            }
          case 146: break;
          case 42: 
            { return alloy_sym(yytext(), CompSym.NFEAT8       );
            }
          case 147: break;
          case 43: 
            { return alloy_sym(yytext(), CompSym.NFEAT9       );
            }
          case 148: break;
          case 44: 
            { throw new ErrorSyntax(alloy_here(yytext()),"String literal is missing its closing \" character");
            }
          case 149: break;
          case 45: 
            { 
            }
          case 150: break;
          case 46: 
            { return alloy_num (yytext());
            }
          case 151: break;
          case 47: 
            { return alloy_sym(yytext(), CompSym.AND         );
            }
          case 152: break;
          case 48: 
            { return alloy_sym(yytext(), CompSym.PLUSPLUS    );
            }
          case 153: break;
          case 49: 
            { return alloy_sym(yytext(), CompSym.ARROW       );
            }
          case 154: break;
          case 50: 
            { return alloy_sym(yytext(), CompSym.SHA         );
            }
          case 155: break;
          case 51: 
            { return alloy_sym(yytext(), CompSym.GTE         );
            }
          case 156: break;
          case 52: 
            { return alloy_sym(yytext(), CompSym.RANGE       );
            }
          case 157: break;
          case 53: 
            { return alloy_sym(yytext(), CompSym.DOMAIN      );
            }
          case 158: break;
          case 54: 
            { return alloy_sym(yytext(), CompSym.SHL         );
            }
          case 159: break;
          case 55: 
            { return alloy_sym(yytext(), CompSym.LTE         );
            }
          case 160: break;
          case 56: 
            { return alloy_sym(yytext(), CompSym.IMPLIES     );
            }
          case 161: break;
          case 57: 
            { return alloy_sym(yytext(), CompSym.OR          );
            }
          case 162: break;
          case 58: 
            { return alloy_sym(yytext(), CompSym.AS          );
            }
          case 163: break;
          case 59: 
            { return alloy_sym(yytext(), CompSym.NO          );
            }
          case 164: break;
          case 60: 
            { return alloy_sym(yytext(), CompSym.IN          );
            }
          case 165: break;
          case 61: 
            { return alloy_sym(yytext(), CompSym.PFEAT0       );
            }
          case 166: break;
          case 62: 
            { return alloy_sym(yytext(), CompSym.NFEAT0       );
            }
          case 167: break;
          case 63: 
            { return alloy_string(yytext());
            }
          case 168: break;
          case 64: 
            { throw new ErrorSyntax(alloy_here(yytext()),"Name cannot start with a number.");
            }
          case 169: break;
          case 65: 
            { return alloy_sym(yytext(), CompSym.SHR         );
            }
          case 170: break;
          case 66: 
            { return alloy_sym(yytext(), CompSym.IFF         );
            }
          case 171: break;
          case 67: 
            { return alloy_sym(yytext(), CompSym.ALL         );
            }
          case 172: break;
          case 68: 
            { return alloy_sym(yytext(), CompSym.BUT         );
            }
          case 173: break;
          case 69: 
            { return alloy_sym(yytext(), CompSym.SET         );
            }
          case 174: break;
          case 70: 
            { return alloy_sym(yytext(), CompSym.SEQ         );
            }
          case 175: break;
          case 71: 
            { return alloy_sym(yytext(), CompSym.SUM         );
            }
          case 176: break;
          case 72: 
            { return alloy_sym(yytext(), CompSym.SIG         );
            }
          case 177: break;
          case 73: 
            { return alloy_sym(yytext(), CompSym.RUN         );
            }
          case 178: break;
          case 74: 
            { return alloy_sym(yytext(), CompSym.LET         );
            }
          case 179: break;
          case 75: 
            { return alloy_sym(yytext(), CompSym.EXH         );
            }
          case 180: break;
          case 76: 
            { return alloy_sym(yytext(), CompSym.INT         );
            }
          case 181: break;
          case 77: 
            { return alloy_sym(yytext(), CompSym.ONE         );
            }
          case 182: break;
          case 78: 
            { return alloy_sym(yytext(), CompSym.FUN         );
            }
          case 183: break;
          case 79: 
            { return alloy_sym(yytext(), CompSym.FOR         );
            }
          case 184: break;
          case 80: 
            { return alloy_sym(yytext(), CompSym.SIGINT      );
            }
          case 185: break;
          case 81: 
            { throw new ErrorSyntax(alloy_here(yytext()),"String literal cannot be followed by a legal identifier character.");
            }
          case 186: break;
          case 82: 
            { return alloy_binarynum (yytext());
            }
          case 187: break;
          case 83: 
            { return alloy_hexnum (yytext());
            }
          case 188: break;
          case 84: 
            { return alloy_sym(yytext(), CompSym.SOME        );
            }
          case 189: break;
          case 85: 
            { return alloy_sym(yytext(), CompSym.THIS        );
            }
          case 190: break;
          case 86: 
            { return alloy_sym(yytext(), CompSym.LONE        );
            }
          case 191: break;
          case 87: 
            { return alloy_sym(yytext(), CompSym.NONE        );
            }
          case 192: break;
          case 88: 
            { return alloy_sym(yytext(), CompSym.DISJ        );
            }
          case 193: break;
          case 89: 
            { return alloy_sym(yytext(), CompSym.ELSE        );
            }
          case 194: break;
          case 90: 
            { return alloy_sym(yytext(), CompSym.ENUM        );
            }
          case 195: break;
          case 91: 
            { return alloy_sym(yytext(), CompSym.UNIV        );
            }
          case 196: break;
          case 92: 
            { return alloy_sym(yytext(), CompSym.IDEN        );
            }
          case 197: break;
          case 93: 
            { return alloy_sym(yytext(), CompSym.OPEN        );
            }
          case 198: break;
          case 94: 
            { return alloy_sym(yytext(), CompSym.PART        );
            }
          case 199: break;
          case 95: 
            { return alloy_sym(yytext(), CompSym.PRED        );
            }
          case 200: break;
          case 96: 
            { return alloy_sym(yytext(), CompSym.FACT        );
            }
          case 201: break;
          case 97: 
            { return alloy_sym(yytext(), CompSym.CHECK       );
            }
          case 202: break;
          case 98: 
            { return alloy_sym(yytext(), CompSym.ASSERT      );
            }
          case 203: break;
          case 99: 
            { return alloy_sym(yytext(), CompSym.EXPECT      );
            }
          case 204: break;
          case 100: 
            { return alloy_sym(yytext(), CompSym.MODULE      );
            }
          case 205: break;
          case 101: 
            { return alloy_sym(yytext(), CompSym.STRING      );
            }
          case 206: break;
          case 102: 
            { return alloy_sym(yytext(), CompSym.EXACTLY     );
            }
          case 207: break;
          case 103: 
            { return alloy_sym(yytext(), CompSym.EXTENDS     );
            }
          case 208: break;
          case 104: 
            { return alloy_sym(yytext(), CompSym.PRIVATE     );
            }
          case 209: break;
          case 105: 
            { return alloy_sym(yytext(), CompSym.ABSTRACT    );
            }
          case 210: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
